### ISSUE TITLE
NativeExists(const name[])

### ISSUE THREAD

**Issue by Y-Less** [IllidanS4/NativeFallback#1]
I've long wanted a runtime way to detect this, to customise behaviour based on loaded plugins.  Unfortunately I've never been able to come up with a pure pawn solution, since they are checked before any code is run.  This of course makes a chicken-and-egg problem, since you then need a plugin to detect if a plugin exists, and what if the detection plugin doesn't exist?

Despite that, it would be useful.

**Comment by IS4Code** [comment]
Based on our previous discussion, `NativeExists` and `MapNative` were added, but they use special calls to `getproperty` so that they work in a correct fashion even if the plugin is not loaded.

`NativeExists` returns true if other plugins exported the specified native, and `MapNative` creates a local script mapping between a negative native index and the native. Calling a negative index will replace it with the mapped function (if found in the map).

If `MapNative` does not find the function, it returns false, but still generates a fallback function in the case the user code behaves incorrectly.
